import { BarChart3, Bot, CalendarCheck, CloudCog, Compass, Headphones, Heart, Hotel, Layers3, PanelsTopLeft, Rocket, Search, ShieldCheck, Smartphone, Sparkles, UserRound, WalletCards } from 'lucide-react';
import type { Slide } from './types';

export const slides: Slide[] = [
  { eyebrow: 'Next Tour · Kazakhstan', title: 'Путешествия нового поколения', lead: 'Единый сервис поиска, сравнения и бронирования туров с автоматической синхронизацией туроператоров.', visual: 'cover', icon: Compass },
  { eyebrow: '01 · О проекте', title: 'Всё путешествие — в одном сервисе', lead: 'Цифровая платформа, которая делает выбор тура понятным, быстрым и персональным.', visual: 'overview', points: ['Поиск и сравнение цен', 'Онлайн-бронирование', 'Личный кабинет', 'PWA-приложение'], metric: '24/7', metricLabel: 'доступ к путешествиям', icon: Layers3 },
  { eyebrow: '02 · Главная страница', title: 'Вдохновение встречается с технологией', lead: 'Маршрут начинается с простого поиска — всё важное уже рядом.', visual: 'home', points: ['Город вылета', 'Горящие туры', 'Отзывы туристов', 'AI-подбор'], icon: PanelsTopLeft },
  { eyebrow: '03 · Умный поиск', title: 'Лучший тур — среди всех операторов', lead: 'Мгновенная фильтрация по стране, курорту, датам, питанию, цене, звёздам и оператору.', visual: 'search', metric: '8', metricLabel: 'точных фильтров', icon: Search },
  { eyebrow: '04 · Интеграции', title: 'Цены всегда актуальны', lead: 'Selfie Travel, Kompas Tour, FSTRAVEL и Pegas Touristik работают как единый каталог.', visual: 'sync', points: ['Обновление каждый час', 'Дубликаты отелей объединяются', 'Система выбирает лучшую цену'], icon: CloudCog },
  { eyebrow: '05 · Онлайн-бронирование', title: 'От выбора до заявки — шесть шагов', lead: 'Прозрачный процесс без звонков, потерянных сообщений и лишнего ожидания.', visual: 'booking', icon: CalendarCheck },
  { eyebrow: '06 · Аккаунт', title: 'Личное пространство путешественника', lead: 'Бронирования, избранное, история поездок, price alerts и бонусы всегда под рукой.', visual: 'account', points: ['Мои бронирования', 'Избранные туры', 'История путешествий', 'Снижение цены'], icon: UserRound },
  { eyebrow: '07 · Next AI', title: 'Опишите мечту. Мы найдём маршрут.', lead: 'Интеллектуальный помощник понимает свободный запрос и мгновенно предлагает подходящие туры.', visual: 'ai', icon: Bot },
  { eyebrow: '08 · Mobile first', title: 'Сайт, который ощущается приложением', lead: 'Свайпы, ripple-анимации, нижнее меню и быстрые переходы — с первого касания.', visual: 'mobile', points: ['iPhone & Android', 'PWA ready', 'Touch-first UX'], icon: Smartphone },
  { eyebrow: '09 · Admin OS', title: 'Центр управления Next Tour', lead: 'Продажи, каталог, клиенты и поддержка собраны в одной понятной системе.', visual: 'admin', icon: BarChart3 },
  { eyebrow: '10 · Управление турами', title: 'Каталог под полным контролем', lead: 'Добавляйте туры, меняйте цены и фотографии, запускайте акции и управляйте доступностью.', visual: 'editor', points: ['Редактор контента', 'Управление акциями', 'Популярные предложения'], icon: Hotel },
  { eyebrow: '11 · Бронирования', title: 'Каждая заявка — в правильном статусе', lead: 'Менеджер видит путь заявки от первого обращения до подтверждённой поездки.', visual: 'bookings', icon: WalletCards },
  { eyebrow: '12 · Поддержка', title: 'Диалог с клиентом без потерь', lead: 'Сообщения мгновенно сохраняются, а Telegram и WhatsApp держат команду в курсе.', visual: 'support', points: ['Файлы и история', 'Быстрые шаблоны', 'Мессенджер-уведомления'], icon: Headphones },
  { eyebrow: '13 · Аналитика', title: 'Бизнес виден в реальном времени', lead: 'Посетители, заявки, конверсия, средний чек и продажи превращаются в ясные решения.', visual: 'analytics', metric: '18.4%', metricLabel: 'конверсия в заявку', icon: BarChart3 },
  { eyebrow: '14 · Безопасность', title: 'Доверие встроено в архитектуру', lead: 'HTTPS, JWT, роли доступа, резервные копии и аудит действий защищают каждый уровень.', visual: 'security', points: ['API-ключи в .env', 'Защищённая админ-панель', 'Резервное копирование'], icon: ShieldCheck },
  { eyebrow: '15 · Технологии', title: 'Архитектура, готовая к росту', lead: 'Современный стек объединяет быстрый интерфейс, надёжные данные и облачную инфраструктуру.', visual: 'architecture', icon: Layers3 },
  { eyebrow: '16 · Преимущество', title: 'Не агентство. Технологическая платформа.', lead: 'Next Tour автоматизирует то, что традиционный рынок всё ещё делает вручную.', visual: 'compare', icon: Sparkles },
  { eyebrow: '17 · Roadmap', title: 'Следующая точка назначения', lead: 'Оплата, ваучеры, бонусы и AI-консультант превращают сервис в полноценную travel-экосистему.', visual: 'roadmap', icon: Rocket },
  { eyebrow: 'Next Tour · 2026', title: 'Путешествия начинаются здесь', lead: 'Современная цифровая экосистема для поиска, сравнения и бронирования туров в Казахстане.', visual: 'final', points: ['Telegram', 'Instagram', 'hello@nexttour.kz'], icon: Heart },
];
