import { BarChart3, Bell, CalendarDays, CircleUserRound, Cloud, FileText, Headphones, LayoutDashboard, MessageCircle, Plane, Plus, Search, Settings, UsersRound } from 'lucide-react';
import type { VisualKind } from './types';

const nav = [[LayoutDashboard,'Дашборд'],[Plane,'Туры'],[CalendarDays,'Бронирования'],[UsersRound,'Пользователи'],[Headphones,'Поддержка'],[Cloud,'Синхронизация'],[BarChart3,'Аналитика'],[Settings,'Настройки']] as const;
function AdminShell({ children, active='Дашборд' }: { children: React.ReactNode; active?: string }) { return <div className="p-admin"><aside><b>n<span>t</span></b>{nav.map(([Icon,label])=><i className={label===active?'active':''} key={label}><Icon/>{label}</i>)}</aside><main><header><div><small>ЦЕНТР УПРАВЛЕНИЯ</small><b>{active}</b></div><span><Bell/></span><span className="p-admin-avatar">AK</span></header>{children}</main></div>; }
function AdminVisual() { return <AdminShell><div className="p-kpis">{[['₸ 12.8M','Продажи'],['248','Заявки'],['18.4%','Конверсия']].map(x=><div key={x[1]}><small>{x[1]}</small><b>{x[0]}</b><em>↗ 12%</em></div>)}</div><div className="p-chart"><div className="p-bars">{[42,57,48,76,64,91,84,100,82,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></AdminShell>; }
function EditorVisual() { return <AdminShell active="Туры"><div className="p-editor"><div className="p-editor-head"><div><b>Rixos Premium Belek</b><small>Турция · Анталья</small></div><button><Plus/> Добавить тур</button></div><div className="p-form-grid"><label>Название<input value="Rixos Premium Belek" readOnly/></label><label>Цена<input value="382 000 ₸" readOnly/></label><label>Страна<input value="Турция" readOnly/></label><label>Питание<input value="Всё включено" readOnly/></label></div><div className="p-image-field"><FileText/><span>hero-rixos.jpg<small>1920 × 1080 · 1.4 MB</small></span><button>Заменить</button></div></div></AdminShell>; }
function BookingsVisual() { return <AdminShell active="Бронирования"><div className="p-table-head"><div className="p-table-search"><Search/> Поиск туриста</div><button>Все статусы</button></div><div className="p-table">{[['Ахмед С.','Турция','12.09','Подтверждена','green'],['Алина К.','Египет','20.09','Новая заявка','yellow'],['Дана Р.','ОАЭ','24.09','В обработке','blue'],['Илья М.','Турция','02.10','Отменена','red']].map(r=><div key={r[0]}><span><CircleUserRound/>{r[0]}</span><span>{r[1]}</span><span>{r[2]}</span><b className={r[4]}>{r[3]}</b></div>)}</div></AdminShell>; }
function SupportVisual() { return <div className="p-support"><aside><div className="p-support-title"><b>Обращения</b><span>12</span></div>{['Алина Касымова','Ахмед Садыков','Дана Рахимова'].map((n,i)=><div className={i===0?'active':''} key={n}><span>{n[0]}</span><p><b>{n}</b><small>{i===0?'Подскажите по трансферу…':'Спасибо, всё понятно!'}</small></p><time>12:{42-i*8}</time></div>)}</aside><main><header><span>А</span><div><b>Алина Касымова</b><small>Telegram · онлайн</small></div></header><div className="p-support-msg client">Подскажите, трансфер из аэропорта входит в стоимость?</div><div className="p-support-msg manager">Да, групповой трансфер уже включён ✨</div><div className="p-support-input">Написать сообщение…<MessageCircle/></div></main></div>; }
function AnalyticsVisual() { return <AdminShell active="Аналитика"><div className="p-kpis compact">{[['24.8K','Посетители'],['1 284','Заявки'],['₸ 684K','Средний чек']].map(x=><div key={x[1]}><small>{x[1]}</small><b>{x[0]}</b><em>↗</em></div>)}</div><div className="p-analytics"><div><small>ПРОДАЖИ ЗА 30 ДНЕЙ</small><svg viewBox="0 0 600 170" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#46e6b0" stopOpacity=".4"/><stop offset="1" stopColor="#46e6b0" stopOpacity="0"/></linearGradient></defs><path d="M0 145 C70 120 90 150 150 105 S240 125 285 75 S380 100 420 52 S510 78 600 20 L600 170 L0 170Z" fill="url(#area)"/><path d="M0 145 C70 120 90 150 150 105 S240 125 285 75 S380 100 420 52 S510 78 600 20" fill="none" stroke="#46e6b0" strokeWidth="4"/></svg></div><div className="p-donut"><i/><b>64%</b><small>Турция</small></div></div></AdminShell>; }
export function BusinessVisual({ kind }: { kind: VisualKind }) { if(kind==='editor')return <EditorVisual/>;if(kind==='bookings')return <BookingsVisual/>;if(kind==='support')return <SupportVisual/>;if(kind==='analytics')return <AnalyticsVisual/>;return <AdminVisual/>; }
