import { Bot, Check, Cloud, Code2, Database, Globe2, LockKeyhole, Plane, RefreshCw, Server, Shield, Smartphone, Sparkles, WalletCards, X } from 'lucide-react';
import type { VisualKind } from './types';
import { PlaneRoute, TourCard } from './VisualPrimitives';

const operators = ['SELFIE', 'KOMPAS', 'FSTRAVEL', 'PEGAS'];
function CoverVisual() { return <div className="p-cover-visual"><div className="p-orbit one"/><div className="p-orbit two"/><div className="p-globe"><Globe2/></div><div className="p-float-card card-a"><small>АЛМАТЫ → АНТАЛЬЯ</small><b>12 сентября</b><PlaneRoute/></div><div className="p-float-card card-b"><small>ЛУЧШАЯ ЦЕНА</small><b>382 000 ₸</b><em>−18% сегодня</em></div></div>; }
function OverviewVisual() { return <div className="p-overview"><div className="p-overview-photo"/><div className="p-overview-card"><small>ЕДИНАЯ ПЛАТФОРМА</small><h3>Найти. Сравнить.<br/>Забронировать.</h3><div><span><Globe2/> 12 стран</span><span><WalletCards/> онлайн-бронь</span><span><Bot/> Next AI</span></div></div><TourCard/></div>; }
function SyncVisual() { return <div className="p-sync"><div className="p-operators">{operators.map((o,i)=><div key={o}><span>{o[0]}</span><b>{o}</b><small>{[482,318,406,295][i]} туров</small></div>)}</div><div className="p-sync-line"><i/><RefreshCw/><i/></div><div className="p-database"><Database/><div><b>Next Tour Data Core</b><small>1 501 предложение · обновлено 8 мин назад</small></div><em>LIVE</em></div><div className="p-sync-stats"><span><Check/> Дубликаты объединены</span><span><Check/> Лучшая цена выбрана</span><span><RefreshCw/> Обновление каждый час</span></div></div>; }
function SecurityVisual() { return <div className="p-security"><div className="p-shield"><Shield/><LockKeyhole/></div>{[['HTTPS','Шифрование трафика'],['JWT','Безопасные сессии'],['RBAC','Роли и доступ'],['BACKUP','Резервные копии'],['AUDIT','История действий']].map((x,i)=><div className={`p-sec-node n${i+1}`} key={x[0]}><i><Check/></i><span><b>{x[0]}</b><small>{x[1]}</small></span></div>)}</div>; }
function ArchitectureVisual() { const groups=[[Code2,'Frontend',['React','TypeScript','Tailwind','Framer Motion']],[Server,'Backend',['FastAPI / Node.js','PostgreSQL','Redis','Celery / BullMQ']],[Cloud,'Infrastructure',['Cloud VPS','CDN','Auto deploy','Monitoring']]] as const; return <div className="p-architecture">{groups.map(([Icon,title,items],i)=><div key={title}><span className={`tone-${i}`}><Icon/></span><small>0{i+1}</small><h3>{title}</h3>{items.map(item=><p key={item}>{item}<Check/></p>)}</div>)}</div>; }
function CompareVisual() { const old=['Ручное обновление цен','Нет онлайн-брони','Нет аналитики','Слабая мобильная версия']; const fresh=['Автоматические цены','Все операторы в одном месте','AI-подбор тура','Онлайн-бронирование','Мощная админ-панель','Mobile-first UX']; return <div className="p-compare"><div className="old"><small>ОБЫЧНОЕ АГЕНТСТВО</small><h3>Ручные процессы</h3>{old.map(x=><p key={x}><X/>{x}</p>)}</div><div className="new"><div className="p-mini-brand">next<span>tour</span></div><h3>Цифровая система</h3>{fresh.map(x=><p key={x}><Check/>{x}</p>)}</div></div>; }
function RoadmapVisual() { const items=[['Сейчас','PWA-приложение',Smartphone],['Q4','Kaspi Pay',WalletCards],['2027','AI 24/7',Bot],['Next','RU · KZ · EN',Globe2]] as const; return <div className="p-roadmap"><div className="p-road-line"/>{items.map(([date,title,Icon],i)=><div key={title} className={i===0?'active':''}><small>{date}</small><span><Icon/></span><h3>{title}</h3><p>{['Push и бонусы','Оплата и ваучеры','Персональный консьерж','Новые рынки'][i]}</p></div>)}</div>; }
function FinalVisual() { return <div className="p-final-mark"><div className="p-final-glow"/><Plane/><div className="p-final-line"/><Sparkles/></div>; }
export function StoryVisual({ kind }: { kind: VisualKind }) { if(kind==='cover')return <CoverVisual/>;if(kind==='overview')return <OverviewVisual/>;if(kind==='sync')return <SyncVisual/>;if(kind==='security')return <SecurityVisual/>;if(kind==='architecture')return <ArchitectureVisual/>;if(kind==='compare')return <CompareVisual/>;if(kind==='roadmap')return <RoadmapVisual/>;return <FinalVisual/>; }
