import { CheckCircle2, Quote, Star } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useReviews } from '../hooks/useReviews';

export function Reviews() {
  const { reviews, addReview } = useReviews();
  const [name, setName] = useState(''); const [text, setText] = useState(''); const [rating, setRating] = useState(5); const [sent, setSent] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); try { await addReview({ name: name.trim(), text: text.trim(), rating }); setName(''); setText(''); setSent(true); } catch { setSent(false); } }
  const published = reviews.filter(review => review.status === 'published');
  return <section id="reviews" className="section-shell scroll-mt-24 py-24"><div className="mb-10 text-center"><p className="mb-3 text-xs font-black uppercase tracking-[.2em] text-brand-dark">Нам доверяют</p><h2 className="text-3xl font-black tracking-[-.04em] sm:text-5xl">Отдых, о котором рассказывают</h2></div><div className="grid gap-5 md:grid-cols-3">{published.slice(0, 6).map(review => <article key={review.id} className="relative rounded-[26px] border border-slate-100 bg-white p-7 shadow-[0_12px_40px_rgba(7,29,52,.06)]"><Quote className="absolute right-6 top-6 size-10 text-brand/15"/><div className="flex gap-1 text-amber-400">{Array.from({ length: review.rating }, (_, index) => <Star key={index} className="size-4 fill-current"/>)}</div><p className="mt-6 leading-7 text-slate-600">«{review.text}»</p><p className="mt-7 font-extrabold text-navy">{review.name}</p><p className="text-xs text-slate-400">Клиент Next Tour · {new Date(review.createdAt).toLocaleDateString('ru-RU')}</p></article>)}</div>
    <div className="mx-auto mt-12 max-w-2xl rounded-3xl bg-mist p-6 sm:p-8"><h3 className="text-2xl font-black text-navy">Оставить отзыв</h3>{sent && <p className="mt-3 flex items-center gap-2 rounded-xl bg-brand/10 p-3 text-sm font-bold text-brand-dark"><CheckCircle2 className="size-5"/>Спасибо! Отзыв отправлен на модерацию.</p>}<form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-[1fr_140px]"><input required value={name} onChange={event => setName(event.target.value)} placeholder="Ваше имя" className="h-12 rounded-xl border border-slate-200 px-4 outline-none focus:border-brand"/><select value={rating} onChange={event => setRating(Number(event.target.value))} className="h-12 rounded-xl border border-slate-200 px-3 font-bold outline-none focus:border-brand">{[5,4,3,2,1].map(value => <option key={value} value={value}>{value} ★</option>)}</select><textarea required minLength={10} value={text} onChange={event => setText(event.target.value)} placeholder="Расскажите о поездке" rows={4} className="rounded-xl border border-slate-200 p-4 outline-none focus:border-brand sm:col-span-2"/><button className="rounded-xl bg-brand px-6 py-3 font-extrabold text-white hover:bg-brand-dark sm:col-span-2">Отправить отзыв</button></form></div>
  </section>;
}
